### ISSUE TITLE
执行 php artisan 的时候出错

### ISSUE THREAD

**Issue by feymanlee** [lawoole/lawoole#1]
```
PHP Fatal error:  Uncaught ReflectionException: Class config does not exist in /Users/feyman/code/lawoole/vendor/illuminate/container/Container.php:752
Stack trace:
#0 /Users/feyman/code/lawoole/vendor/illuminate/container/Container.php(752): ReflectionClass->__construct('config')
#1 /Users/feyman/code/lawoole/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build('config')
#2 /Users/feyman/code/lawoole/vendor/illuminate/container/Container.php(586): Illuminate\Container\Container->resolve('config', Array)
#3 /Users/feyman/code/lawoole/vendor/illuminate/container/Container.php(1195): Illuminate\Container\Container->make('config')
#4 /Users/feyman/code/lawoole/vendor/lawoole/framework/src/Providers/ArtisanServiceProvider.php(97): Illuminate\Container\Container->offsetGet('config')
#5 /Users/feyman/code/lawoole/vendor/lawoole/framework/src/Application.php(451): Lawoole\Providers\ArtisanServiceProvider->register()
#6 /Users/feyman/code/lawoole/vendor/illuminate/support/AggregateServiceProvider.php(3 in /Users/feyman/code/lawoole/vendor/illuminate/container/Container.php on line 752
```

**Comment by youmingdot** [comment]
您好，这是一个已知的问题，原因是 artisan 和 server 入口提前注册服务造成的。这个问题已经修复，请参考  https://github.com/lawoole/lawoole/releases  最新的版本重新定义项目。感谢您的反馈。  
 
------------------ Original ------------------
From: "Feyman"; 
Date: 2018年2月2日(星期五) 凌晨1:00
To: "lawoole/lawoole"; 
Cc: "Subscribed"; 
Subject: [lawoole/lawoole] 执行 php artisan 的时候出错 (#1)

 
PHP Fatal error:  Uncaught ReflectionException: Class config does not exist in /Users/feyman/code/lawoole/vendor/illuminate/container/Container.php:752 Stack trace: #0 /Users/feyman/code/lawoole/vendor/illuminate/container/Container.php(752): ReflectionClass->__construct('config') #1 /Users/feyman/code/lawoole/vendor/illuminate/container/Container.php(631): Illuminate\Container\Container->build('config') #2 /Users/feyman/code/lawoole/vendor/illuminate/container/Container.php(586): Illuminate\Container\Container->resolve('config', Array) #3 /Users/feyman/code/lawoole/vendor/illuminate/container/Container.php(1195): Illuminate\Container\Container->make('config') #4 /Users/feyman/code/lawoole/vendor/lawoole/framework/src/Providers/ArtisanServiceProvider.php(97): Illuminate\Container\Container->offsetGet('config') #5 /Users/feyman/code/lawoole/vendor/lawoole/framework/src/Application.php(451): Lawoole\Providers\ArtisanServiceProvider->register() #6 /Users/feyman/code/lawoole/vendor/illuminate/support/AggregateServiceProvider.php(3 in /Users/feyman/code/lawoole/vendor/illuminate/container/Container.php on line 752

**Comment by feymanlee** [comment]
升级到了 0.1.4 还是有这个问题

**Comment by youmingdot** [comment]
https://github.com/lawoole/lawoole 里的 artisan 和 server 两个文件的内容，有做修改，请参考一下进行更正，最好是整个项目重新拉取 https://github.com/lawoole/lawoole 的内容
