### ISSUE TITLE
是打算放弃 laravel .env 的配置方式吗？把配置写死在配置文件中不是一个好的实践啊

### ISSUE THREAD

**Issue by feymanlee** [lawoole/lawoole#3]

**Comment by youmingdot** [comment]
不，Lawoole 提供了比 .env 更可扩展性的配置方式，只需要在 config/environment 中使用同 scope 文件进行配置即可。

![tim 20180202163443](https://user-images.githubusercontent.com/6078171/35723937-002a63ee-0837-11e8-9e4a-f69e5a1d8c1e.png)

**Comment by feymanlee** [comment]
感觉这样需要维护很多个配置文件，还是不如采用 .env 的方式方便，这样做是因为对性能的提升有好处吗？没有仔细研究你的实现

**Comment by youmingdot** [comment]
首先，.env 无法定义数组等复杂结构，其次，.env 无法对复杂的层次结构进行替换。
而这些，在 environment 中都可以实现。

例如，替换数组
```
return [
    'providers' => [
        // 完全替换之前的定义
    ]
];
```

又如，附加配置
```
return [
    'providers' => function ($providers) {
        // $providers 是根 config 配置的值
        $providers[] = AppServiceProvider::class;
        
        return $providers;
    }
];
```

**Comment by godruoyi** [comment]
多个不同环境的配置文件怎么实现呢
![image](https://user-images.githubusercontent.com/16079222/51736616-74b25080-20c5-11e9-8efc-487895673938.png)
