### ISSUE TITLE
对lawoole的一些建议和意见

### ISSUE THREAD

**Issue by xiaohuilam** [lawoole/lawoole#6]
1. 是否应该把 github 的 project 管理用起来，管理接下来的计划和todo list
2. db、model和cache这几个重度使用的类，目前还没有实现

希望这个项目能一直这个高质量下去

**Comment by youmingdot** [comment]
@xiaohuilam Lawoole 并不是一个从零开始的框架，其只是桥接了 Swoole 和 Laravel，将它们之间的隔阂消除。对于 DB 、Model、Cache 等模块，开发者依然可以使用 Laravel 中的实现。我们并不是重新开发框架，而仅是站在巨人的肩膀上。
