### ISSUE TITLE
既然是基于laravel和swoole，那么有没有把laravel底层的mysql组件换成swoole_mysql?

### ISSUE THREAD

**Issue by mountainguan** [lawoole/lawoole#7]
因为直接让laravel具有更高的响应效率这个问题，其他很多项目都有组件化的方案了。既然这边是重组一个框架，那么是不是应该把底层的一个工具用上呢？诸如swoole_mysql这些连接池功能能有效提高项目整体性能。

**Comment by youmingdot** [comment]
@mountainguan 很遗憾， Lawoole 暂时没有替换 Laravel 底层 MySQL 驱动的想法。首先，Laravel 本身的 MySQL 驱动是基于 PDO 的，其效率并不会太差。另外，swoole_mysql 功能过于简单，甚至连预处理语句的功能都缺乏，对于拥有丰富功能的 Laravel Database 模块来说，这样的基础设施是完全不够的。

**Comment by mountainguan** [comment]
那新版swoole的连接池功能呢

**Comment by GStepOne** [comment]
大哥 你这文档没有 不知道怎么下手啊。
